### ISSUE TITLE
Change to .env reference to prevent api key hijacking

### ISSUE THREAD

**Issue by andytcf** [affaxltd/teslaswap#3]
https://github.com/affaxltd/teslaswap/blob/bcfd5762548af2848d40ac0087863722749cd230/src/lib/web3/providers.ts#L14

**Comment by affaxltd** [comment]
Actually funnily enough I already deauthorized that api key before but it will always be able to be hijacked in the site as I have to somehow give WalletConnect a valid RPC URL
